# Generated by Django 3.2.5 on 2021-07-29 15:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Assignmentapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assignments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assg_no', models.IntegerField(unique=True, verbose_name='Assignment No')),
                ('assg_title', models.CharField(max_length=255, verbose_name='Assignment Title')),
                ('assg_file', models.FileField(upload_to='AssignmentFiles')),
                ('assg_createdtime', models.DateTimeField(auto_now_add=True)),
                ('assg_deadline', models.DateTimeField()),
                ('assg_marks', models.IntegerField(verbose_name='Marks')),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dept_name', models.CharField(max_length=40, verbose_name='Department Name')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stud_roll', models.IntegerField(unique=True, verbose_name='Student Roll No')),
                ('dept', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Assignmentapp.department', verbose_name='Student Department')),
                ('user_ref', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='User Details')),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dept', models.ManyToManyField(blank=True, null=True, related_name='teacher_dept', to='Assignmentapp.Department')),
                ('user_ref', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_reference', to=settings.AUTH_USER_MODEL, verbose_name='User Details')),
            ],
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submittime', models.DateTimeField(auto_now_add=True)),
                ('submission_file', models.FileField(upload_to='SubmittedFiles')),
                ('assg_ref', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assignment_ref', to='Assignmentapp.assignments', verbose_name='Assignment Details')),
                ('stud_ref', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_ref', to='Assignmentapp.student', verbose_name='Student Details')),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_name', models.CharField(max_length=40, verbose_name='Subject Name')),
                ('dept_ref', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='department_ref', to='Assignmentapp.department', verbose_name='Department Name')),
            ],
        ),
        migrations.AddField(
            model_name='assignments',
            name='sub_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Assignmentapp.subject', verbose_name='Subject Details'),
        ),
    ]
