# Generated by Django 3.2.5 on 2021-07-29 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Assignmentapp', '0003_alter_teacher_dept'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='last_name',
        ),
        migrations.AddField(
            model_name='user',
            name='user_full_name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
