# Generated by Django 3.2.5 on 2021-07-29 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Assignmentapp', '0004_auto_20210729_2157'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='department',
            options={'verbose_name_plural': 'Departments'},
        ),
    ]
