# Generated by Django 3.2.5 on 2021-07-29 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Assignmentapp', '0005_alter_department_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='department',
            options={'verbose_name_plural': '1. Departments'},
        ),
    ]
