# Generated by Django 3.2.5 on 2021-07-31 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Assignmentapp', '0009_auto_20210731_0154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='stud_roll',
            field=models.IntegerField(verbose_name='Student Roll No'),
        ),
    ]
