# Generated by Django 3.2.5 on 2021-07-31 12:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Assignmentapp', '0011_auto_20210731_1819'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='dept_ref',
        ),
        migrations.AddField(
            model_name='subject',
            name='sem_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='semester_ref', to='Assignmentapp.semester', verbose_name='Semester No'),
        ),
    ]
