# Generated by Django 3.2.5 on 2021-07-31 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Assignmentapp', '0012_auto_20210731_1821'),
    ]

    operations = [
        migrations.AddField(
            model_name='semester',
            name='sub_count',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
