# Generated by Django 3.2.5 on 2021-08-04 19:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Assignmentapp', '0014_student_sem_ref'),
    ]

    operations = [
        migrations.AlterField(
            model_name='semester',
            name='dept_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Assignmentapp.department', verbose_name='Department Name'),
        ),
        migrations.AlterField(
            model_name='student',
            name='dept',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Assignmentapp.department', verbose_name='Student Department'),
        ),
        migrations.AlterField(
            model_name='student',
            name='sem_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Assignmentapp.semester', verbose_name='Semester No'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='sem_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Assignmentapp.semester', verbose_name='Semester No'),
        ),
    ]
