# Generated by Django 3.2.5 on 2021-08-04 19:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Assignmentapp', '0015_auto_20210805_0037'),
    ]

    operations = [
        migrations.RenameField(
            model_name='semester',
            old_name='dept_ref',
            new_name='dept',
        ),
    ]
