# Generated by Django 3.2.5 on 2021-08-04 19:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Assignmentapp', '0016_rename_dept_ref_semester_dept'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='sem_ref',
            new_name='semref',
        ),
    ]
