# Generated by Django 3.2.5 on 2021-08-05 14:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Assignmentapp', '0017_rename_sem_ref_student_semref'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subject',
            old_name='sem_ref',
            new_name='semref',
        ),
        migrations.AddField(
            model_name='subject',
            name='dept',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Assignmentapp.department', verbose_name='Department Name'),
        ),
    ]
