# Generated by Django 3.2.5 on 2021-08-05 14:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Assignmentapp', '0018_auto_20210805_1942'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assignments',
            old_name='assg_createdtime',
            new_name='asg_createdtime',
        ),
        migrations.RenameField(
            model_name='assignments',
            old_name='assg_deadline',
            new_name='asg_deadline',
        ),
        migrations.RenameField(
            model_name='assignments',
            old_name='assg_title',
            new_name='asg_title',
        ),
        migrations.RenameField(
            model_name='assignments',
            old_name='sub_ref',
            new_name='subref',
        ),
        migrations.RemoveField(
            model_name='assignments',
            name='assg_file',
        ),
        migrations.RemoveField(
            model_name='assignments',
            name='assg_marks',
        ),
        migrations.RemoveField(
            model_name='assignments',
            name='assg_no',
        ),
        migrations.AddField(
            model_name='assignments',
            name='asg_file',
            field=models.FileField(blank=True, null=True, upload_to='AssignmentFiles'),
        ),
        migrations.AddField(
            model_name='assignments',
            name='asg_marks',
            field=models.IntegerField(blank=True, null=True, verbose_name='Marks'),
        ),
        migrations.AddField(
            model_name='assignments',
            name='asg_no',
            field=models.IntegerField(blank=True, null=True, verbose_name='Assignment No'),
        ),
        migrations.AddField(
            model_name='assignments',
            name='dept',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Assignmentapp.department', verbose_name='Department Name'),
        ),
        migrations.AddField(
            model_name='assignments',
            name='semref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Assignmentapp.semester', verbose_name='Semester No'),
        ),
    ]
