# Generated by Django 3.2.5 on 2021-08-05 14:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Assignmentapp', '0019_auto_20210805_2019'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignments',
            name='teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Assignmentapp.teacher', verbose_name='Teacher Details'),
        ),
    ]
