# Generated by Django 3.2.5 on 2021-08-10 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Assignmentapp', '0020_assignments_teacher'),
    ]

    operations = [
        migrations.RenameField(
            model_name='submission',
            old_name='assg_ref',
            new_name='asgref',
        ),
        migrations.RenameField(
            model_name='submission',
            old_name='stud_ref',
            new_name='studref',
        ),
        migrations.AlterField(
            model_name='submission',
            name='submittime',
            field=models.DateTimeField(),
        ),
    ]
