# Generated by Django 3.2.5 on 2021-08-10 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Assignmentapp', '0021_auto_20210811_0041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='submission_file',
            field=models.FileField(blank=True, null=True, upload_to='SubmittedFiles'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='submittime',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
