# Generated by Django 3.2.5 on 2021-08-10 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Assignmentapp', '0022_auto_20210811_0042'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='submissionstatus',
            field=models.BooleanField(default=False),
        ),
    ]
